// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9CXlfjO630RxARpBSBw4mbCxpygEtr0',
    appId: '1:848175632202:web:d44cc1e67cdd3223cd3bb3',
    messagingSenderId: '848175632202',
    projectId: 'elam-muniafu',
    authDomain: 'elam-muniafu.firebaseapp.com',
    storageBucket: 'elam-muniafu.firebasestorage.app',
    measurementId: 'G-L3B0R08BK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUVokyn3UAaDdg3aqPXynCePquteVJeeU',
    appId: '1:848175632202:android:ca08bb1c363b60b6cd3bb3',
    messagingSenderId: '848175632202',
    projectId: 'elam-muniafu',
    storageBucket: 'elam-muniafu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZluYavze_Aak61FTB8eMtNFk7_LUhQ2k',
    appId: '1:848175632202:ios:a4254c1a2ecbb89dcd3bb3',
    messagingSenderId: '848175632202',
    projectId: 'elam-muniafu',
    storageBucket: 'elam-muniafu.firebasestorage.app',
    iosBundleId: 'com.example.muniafu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZluYavze_Aak61FTB8eMtNFk7_LUhQ2k',
    appId: '1:848175632202:ios:a4254c1a2ecbb89dcd3bb3',
    messagingSenderId: '848175632202',
    projectId: 'elam-muniafu',
    storageBucket: 'elam-muniafu.firebasestorage.app',
    iosBundleId: 'com.example.muniafu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ9CXlfjO630RxARpBSBw4mbCxpygEtr0',
    appId: '1:848175632202:web:a2ad4bb9d0088a14cd3bb3',
    messagingSenderId: '848175632202',
    projectId: 'elam-muniafu',
    authDomain: 'elam-muniafu.firebaseapp.com',
    storageBucket: 'elam-muniafu.firebasestorage.app',
    measurementId: 'G-W1VBQZ57GE',
  );

}